#docker run -d --name redisinsight -p 5540:5540 redis/redisinsight:latest -v redisinsight:/data

services:
    redis:
      image: redis:latest
      container_name: 'redis'
      ports:
        - '6379:6379'
      networks:
        - redis-network
    
    redis-insight:
      image: redis/redisinsight:latest
      container_name: 'redis-insight'
      ports:
        - '5540:5540'
      volumes:
        - 'redisinsight:/data'
      networks:
        - redis-network
      depends_on:
        - redis
        # дополнительно дописать само приложение
  
  
  
networks:
    redis-network:
        driver: bridge
  
volumes:
    redisinsight: